services:
  web:
    build:
      dockerfile: Dockerfile.web
    ports:
      - 8090:8090
    # env_file:
    # - .env
    volumes:
      - ./pb/pb_data:/pb/pb_data
    # - ./${PROJECT_DIR}:/pb/${PROJECT_DIR}
  api:
    build:
      dockerfile: Dockerfile.api
    env_file:
      - .env
    ports:
      - 7777:7777
    volumes:
      #- ./${PROJECT_DIR}:/app/${PROJECT_DIR}
      - ${EMBEDDING_MODEL_PATH}:${EMBEDDING_MODEL_PATH}
